### ISSUE TITLE
xstyled vs styled-system

### ISSUE THREAD

**Issue by agriffis** [gregberge/xstyled#126]
## 💬 Questions and Help

I adopted xstyled into a project without fully understanding its benefits. Now I'd like to get a better understanding so I can make informed decisions going forward.

There are a few places in the documentation that refer to the differences between xstyled and styled-system:

https://xstyled.dev/docs/motivation/
* xstyled is faster
* xstyled can evolve separately from styled-*

https://xstyled.dev/docs/getting-started/
* xstyled `css` can refer to theme values directly in css syntax

https://xstyled.dev/docs/grid-system/
* xstyled includes some help for making grids, which styled-system does not (but similar can be found in the styled-system ecosystem such as [reflexbox](https://rebassjs.org/reflexbox/))

https://xstyled.dev/docs/color-modes/
* xstyled has built-in support for dark mode, although it appears that styled-system may have [gained this abillity now as well](https://styled-system.com/guides/color-modes/)

At this point, it seems that the super-powered `css` function is the main selling point of xstyled. Is that correct, or are there other significant benefits that I'm missing?

**Comment by gregberge** [comment]
Yeah it is correct! I think the website should reflect it. For me xstyled is kind of 'styled-components' with super powers.

**Comment by hc-codersatlas** [comment]
Is there still a big performance difference now that styled-system added some of the changes you proposed?

**Comment by soulchild** [comment]
Piggybacking on this issue, I'd like to know whether xstyled is here to stay? After implementing a design system on top of styled-system and seeing that [Brent Jackson](https://github.com/jxnblk) seems to have taken a break from all his libraries and the Spectrum community is a wasteland, I found xstyled and it seems to be a better fit for my use-case anyways (except for the not yet fully there Typescript support). 

Then I found out that your very own smooth-ui (based on xstyled) has been [abandoned](https://github.com/smooth-code/smooth-ui/issues/174#issuecomment-674405911) as well. 

This all makes me wonder what the hell is going on in the design systems library space. 😄 I'd really like to migrate to xstyled, but it seems to be a tough call…

**Comment by gregberge** [comment]
Hello @soulchild, I am actually working on v2 of xstyled. The core of xstyled is very solid and it is used in production on big projects. So it has proven itself. I am actually working on a better dev experience and documentation.

Stay tuned, but you will not be disappointed!

**Comment by gregberge** [comment]
xstyled v2 is lot of more complete than styled-system, the comparison is no longer relevant.
