### ISSUE TITLE
Compatibility with react native

### ISSUE THREAD

**Issue by rafaelmotta** [gregberge/xstyled#13]
Would be possible to use this project with react-native?. I tried, but I get this error:

`scStyled__default.div is not a function`

I could see under Box.js it's using a div. (https://github.com/smooth-code/xstyled/blob/master/packages/styled-components/src/Box.js#L4) 

Makes sense to create another package to support react-native projects? what do you think? I can *try* to help

**Comment by neoziro** [comment]
Hello @rafaelmotta for now react-native is not supported.

I am interested by adding the support of React Native, the best way would be to expose `@xstyled/styled-components/native`.

I am a react-native user, if someone would want to work on it he is welcome!

**Comment by sislovesmedotcom** [comment]
![Screenshot_20190529-151212](https://user-images.githubusercontent.com/39583750/58536982-7e3ef700-8224-11e9-8e03-ebdeed4c2404.jpg)


+1 
would this project be available for react native in the future ? I also get an error that says 
"scStyled__default.div is not a function"

**Comment by rafaelmotta** [comment]
@neoziro cool. So I will try to implement something in the next days.

**Comment by bidah** [comment]
> Hello @rafaelmotta for now react-native is not supported.
> 
> I am interested by adding the support of React Native, the best way would be to expose `@xstyled/styled-components/native`.
> 
> I am a react-native user, if someone would want to work on it he is welcome!

Well I would also like to add react native to the mix. Just wanna ask if you haven't moved forward with this @neoziro . If not I would be glad to give it a go.

**Comment by neoziro** [comment]
@bidah you are welcome to take it forward, I will not work on it.

**Comment by bidah** [comment]
Hey!, updating about my intention of integration React Native I got a not so good update.
First of all I was unable to setup the DX for developing the addition to the library. Mainly I couldn't run locally the library on a react native project. I did tried out before this my own react native library on react native following in part this reference. (https://callstack.com/blog/adding-an-example-app-to-your-react-native-library/), but this time around I got stucked running the monorepo structure of xstyled. At some point the core library was not detected and couldn't make it run from that point. This without adding to the mix that linking does not work with metro bundler so it was not an option so I got out of options.

Any feedback around this issues is welcomed!

**Comment by bidah** [comment]
So, I ended up using https://github.com/wix/wml to make ti work. For anyone else `wml add` the `src` folder of each of the packages in your local copy of xstyled. e.g `wml add ./xstyled/packages/core/src/ ./xstyled-fork/node_modules/@xstyled/core`

**Comment by bidah** [comment]
Hey @neoziro. So with `wml` linking in place I can now move around add breakpoints and checkout the implementation step by step... still would be great if you could give me some feedback about how you see the addition could go.

**Comment by diegotsi** [comment]
btw, the version `1.11.0`works pretty well on react native

**Comment by Un3qual** [comment]
@diegotsi did you ever find a solution to this?

**Comment by diegotsi** [comment]
> @diegotsi did you ever find a solution to this?

we are using version `1.11.0` and it's working

**Comment by gregberge** [comment]
Still an issue in v2.

**Comment by gregberge** [comment]
To be clear, React Native compatibility will not happen any time soon. I close this issue, feel free to open another if you want to work on it.
