### ISSUE TITLE
@xstyled/system: variant does not use theme

### ISSUE THREAD

**Issue by jguddas** [gregberge/xstyled#136]
## 🐛 Bug Report

variant does not use theme

## To Reproduce

```js
import React from "react";
import { render } from "react-dom";
import styled, { ThemeProvider } from "styled-components";
import { variant } from "@xstyled/system";

const Button = styled.button`
  ${variant({
    prop: "size",
    variants: {
      large: { fontSize: "large" }
    }
  })}
`;

render(
  <ThemeProvider theme={{ fontSizes: { large: "30px" } }}>
    <Button size="large">test!</Button>
  </ThemeProvider>,
  document.getElementById('root')
);
```

results in a button that is styled with

```
font-zize: large
```

## Expected behavior
```
font-zize: 30px
```

## Link to repl

https://codesandbox.io/s/compassionate-solomon-fq4lt

**Comment by xeladejo** [comment]
I think it is the expected behaviour, because "@xstyled/system" don't wrap "styled-components". Try using `th.fontSize("large")`.

**Comment by jguddas** [comment]
We should mention this if this is intended as it deviates from styled-systems's variant behavior.

Same example using styled-systems variant: https://codesandbox.io/s/little-wave-muvsq

**Comment by gregberge** [comment]
Hello @jguddas, yeah you are right I think it is the right behaviour. The `variant` utility need to be refresh, it is actually not very intuitive. I let it opened to know that there is something to do on that.

**Comment by gregberge** [comment]
variant is gone in v2.
