### ISSUE TITLE
Variant utility throws error if no 'default' is defined

### ISSUE THREAD

**Issue by eugeneross** [gregberge/xstyled#154]
## 🐛 Bug Report

When creating a variant using the `variant` utility sometimes there's no need for a default OR I may want to handle the default variant via `PropTypes`. If I don't define a `default` within the variant utility, as shown in the docs, I receive an error saying:

```
variant "undefined" not found
```

## To Reproduce

1. Create a variant using the variant utility.
2. DO NOT define a default variant string.
3. Check console.

## Expected behavior

I would expect the utility to accept a variant without a default in case I want to handle defaults in a different way such as with `PropTypes`

## Link to repl or repo (highly encouraged)

N/A

**Update:** This seems to happen when there are two variant defintions. The way I'm setting up my components is by defining a separate `variants.js` file in my component's folder. Example of variant definition below:

```
import { css } from '@xstyled/styled-components'
import { variant } from '@xstyled/system'

const size = variant({
  prop: 'size',
  // default: 'small',
  variants: {
    large: css`
    
      line-height: 2;
      padding: 2 3;
      height: 9;

      svg {
        width: 7;
        height: 7;
        &:first-of-type {
          margin: 0 1 0 -2;
        }
        &:last-of-type {
          margin: 0 -2 0 auto;
        }
      }

    `,

    small: css`
      font-size: 1;
      padding: 1 2;
      line-height: 2;
      height: 8;

      svg {
        width: 5;
        height: 5;
        &:first-of-type {
          margin-right: 1;
        }
      }

    `
  }
})

// If the second block below is removed, there is no error in the console.

const variants = variant({
  default: 'default', // Commenting out this line will throw an error in the console
  variants: {

    default: css``,

    user: css`
      min-height: 11;
    `,

    detail: css`
      height: auto;
      max-height: 15;
    `,

  }
})

export { size, variants }


```

**Comment by gregberge** [comment]
variant is gone in v2.
