### ISSUE TITLE
Documentation for getting started with emotion is not accurate

### ISSUE THREAD

**Issue by ramyma** [gregberge/xstyled#156]
I noticed that the documentation shown on the website for usage with emotion [here](https://xstyled.dev/docs/emotion/), which is defined [here](https://github.com/gregberge/xstyled/blob/41e73b488a93269098e3289fd97b34c94fd736f6/packages/emotion/README.md), reflects the changes made to an unreleased version other than  v1.19.1.

The latest release ( v1.19.1) still depends on emotion 10 as indicated [here](https://github.com/gregberge/xstyled/blob/v1.19.1/packages/emotion/package.json#L31), but the documentation uses `yarn add @emotion/react` instead which is still due for release.

It's related to the fix applied to this issue https://github.com/gregberge/xstyled/issues/84

**Comment by gregberge** [comment]
Fixed in v2.
