### ISSUE TITLE
CSS selectors with v2 

### ISSUE THREAD

**Issue by ramyma** [gregberge/xstyled#159]
## 💬 CSS selectors with v2 

I was wondering what's the recommended way of applying a CSS selector like `:before` or `:after` in xstyled v2?

**Comment by gregberge** [comment]
Hello @ramyma, the best way to use it is to create a styled component:

```js
import styled from '@xstyled/...'

const Example = styled.div`
  &:before {
    // ...
  }
`
```

This case is not covered by `x` syntax. Alternatively you can create your own utility to be able to style it if you want.
