### ISSUE TITLE
Typescript support is lacking and also hooks return ANY (v2)

### ISSUE THREAD

**Issue by iangregsondev** [gregberge/xstyled#163]
## 🐛 Bug Report

Typescript type support is lacking.

In webstorm it does not recognize the xstyled items, although maybe to do with the styled component plugin

![image](https://user-images.githubusercontent.com/2370364/103888200-a4a56380-50e4-11eb-95d5-bc8ea89ce74b.png)

also, all the hooks take in and return "any" in typescript so there is no type checking

```
  const primary = useColor("primary")
  const primaryx = useTh("colors.primary")
  const theme = useTheme()
```

## To Reproduce
See above

## Expected behavior

It would be nice if it was totally compatible with typescript using the type system that it offers.

**Comment by iangregsondev** [comment]
It would be nice also if you could release a small repo with a test project showing off all the features of typescript as I am not seeing much right now - but maybe I am using it wrong ?

I did create a definition file as per the instructions but was unable to get the "th" method working - seems to accept ONLY strings

![image](https://user-images.githubusercontent.com/2370364/103888950-eda9e780-50e5-11eb-9466-3f5f04fe4ac4.png)


and also the colors in the theming

![image](https://user-images.githubusercontent.com/2370364/103888982-f8647c80-50e5-11eb-81a2-18c5ab4a6582.png)

**Comment by macocha** [comment]
Make sure you also have `@types/styled-components` installed if you are using `styled-components` on top of creating the definition file.

**Comment by gregberge** [comment]
Hi @iangregsondev, typing is not supported in template string because it is not possible to do without an editor plugin. `th` and `useTh` have been forgotten. If someone want to help fixing it, it is welcome!

**Comment by gregberge** [comment]
Fixed in v3.
