### ISSUE TITLE
Emotion/Stylis plugins don't work with style props

### ISSUE THREAD

**Issue by ramyma** [gregberge/xstyled#165]
## 🐛 Bug Report

When a custom cache is used with xstyled/emotion, the `stylisPlugins` provided doesn't work with style props, however, it works with the `styled(Component)`` ` format.

## To Reproduce

Check this example:
https://codesandbox.io/s/unruffled-darkness-su5js?file=/src/App.js

![stylisplugins](https://user-images.githubusercontent.com/14105815/104111673-8a8aa180-52ed-11eb-9d2b-1dbc4aa40475.png)

Notice the first header with an `mr` prop applies a margin right to the element, while the `margin-right` style applied to the `H` component is transformed to `margin-left` on the rendered element.

## Expected behavior

Both style props and `styled(Component)`` ` should use the supplied `stylisPlugins`; in case of the example provided it should flip the margin right to margin left.

**Comment by gregberge** [comment]
Thanks for reporting it!

**Comment by gregberge** [comment]
Fixed in https://github.com/styled-components/stylis-plugin-rtl/releases/tag/2.0.2
