### ISSUE TITLE
xstyled took a sharp turn into the abomination domain

### ISSUE THREAD

**Issue by yairEO** [gregberge/xstyled#176]
as a 2-years "veteran" avid user of xstyled, I saw the new website (and new approach) and was SHOCKED.

as someone which writes CSS for about 20 years, I believe it is a complete abomination to write styles as props on the component themselves and not keep pure separation of concerns between components (or HTML elements) and their styles.

I use styled components in a very complex manner and this new approach is far too basic and promotes dirty coding where developers add a mountain of props, all mixed together, some CSS-related and some logic-related, not to mention it's impossible to properly use & read CSS variables (custom properties) this way.

Your choice where to take xstyled has saddened me greatly and I want to express me feelings so you would know that there is at least one user which is believes this is a mistake. 

Also, the docs are horrible. Cannot find any real information on `th` utility, or real examples of how it can be used (since I never remember)

nor can I find any information regarding extending a an already styled component. The "search" bar of the new website really gives poor results.

**Comment by gregberge** [comment]
Hello @yairEO, thanks for your comment!

To be honest, v2 is not much different from v1, either you choose to use `x.div` or `styled.div` approach. The two were present in v1.

About documentation, it is not perfect but better than v1 I think. What do you suggest to improve it?

**Comment by yairEO** [comment]
1. Add `codesandbox` playgrounds for many of the individual examples
2. Improve the search somehow, because if you type `th` no meaningful results are found

Currently `th` is referenced in the `theme` section, and it should get a much more prominent place in the docs because it's is huge importance when using xstyled.

Typing "methods" or "function" in the search gives nothing and there is no such page in the docs that will present all the possible things which can be imported from `xstyled` library and examples of their usefulness. 

Now with the new homepage, it is completely unknown to a visitor of the truly amazing powers of *xStyled* and I would have ***never*** used it if I had came across the v2 website.

When I first saw v1 website I immediately was so impressed by the usefulness of the examples. For me it was all about typing shortcuts to automatically use things from the theme. like `color: blues.3`, that was amazing.
Also, in v2, there is no more example for theme with array of colors and namespace, only example for `color` property in the theme declared as an Object full of names. it's ok, but at least mention there are other ways as well like the usefulness of array:

```js
const colors = {
  gray: '#646466',  // main gray color
  grays: ['#CCC', '#ECECEC', '#F0F0F0'],  // set of grays from dark to light

  blue: '#0366D6',
  blues: ['#4FA2BC', '#CEE5EC'],

  ...and so on...
}
```

I want to say that I find Tailwind a very **recycled** old idea which already tried and died many times before.  mixing styles inline with HTML is the worst possible thing a developer can do in terms or readability, separation of concerns and working DRY and inability of extending styles.

It might be ok for small personal projects or a website, but in most cases styled component is used in large complex projects, where separation of concerns is critical.

These are my thoughts for now.
I really admire the efforts and your work, just not the path it took

**Comment by SpicyPete** [comment]
I am enjoying using xStyled (both v1 and v2), but I share the concerns with OP.

The updated documentation is nice, but it's very focused on the `x.div` with `props` usage, while I much prefer the `styled.div` form with helpers (th) and short-hand theme variable access.   I try to minimize the props within jsx as much as possible.

My suggestion would be to highlight and add more examples using the `styled` form a bit more in the documentation so it's clear that approach is still equally supported.

**Comment by gregberge** [comment]
I understand, the new version is focus on `x.div` syntax, I think we can improve all documentation by including `styled.div` syntax at the core.

@yairEO @SpicyPete Would you like to help?

**Comment by johot** [comment]
The new approach of v2 is exactly why I love it! I totally disagree with the problems outlined here regarding “separation of concerns” and utility classes/props being for only small projects. I think this article explains things far better than I ever can: https://adamwathan.me/css-utility-classes-and-separation-of-concerns/

**Comment by gregberge** [comment]
Thanks @johot. I understand people love `x.*` and others love `styled.*`. This is why xstyled is supporting both and will continue to support both. The doc should reflect this.

**Comment by AndrewPrifer** [comment]
I agree with @johot, having used Chakra for a recent project, I grew to love style props. The separation of concerns here is really more of a separation of technologies, the same thing React itself was similarly derided for some years ago. I don't know what OP's use case exactly is and how he structures his JSX, but 99% of the time, my intrinsic elements have no props at all when using `styled`. That is because structure, and indeed styling is their primary concern, and style props make that much faster and more streamlined.

That said, transitions like these take time and can't be forced, I think that while the documentation shouldn't be cluttered with with mixing the docs for `x` with the docs of `styled`, `styled` should be more prominently featured to eliminate these concerns.

**Comment by yairEO** [comment]
> @yairEO @SpicyPete Would you like to help?

Sorry my friend, I wish I had time, I am the owner and sole maintainer of countless open-source projects and I have a pile of requests/issues which should be solved.. I do this full-time, not to mention working on new yet-unreleased projects.

**Comment by hwhmeikle** [comment]
@gregberge I am really enjoying my experience with this library so far. It's great to have a maintained successor to styled-system. Keep up the good work!

**Comment by gregberge** [comment]
Hello, the new xstyled v3 unified the two approaches, `styled` is a first class citizen exactly like `x`. The two systems are complementary, feel free to use one or another or both.
