### ISSUE TITLE
size prop overlaps with the <select> element size attribute

### ISSUE THREAD

**Issue by berikiushi** [gregberge/xstyled#177]
## 🐛 Bug Report

`size` prop overlaps with the `<select>` element `size` attribute

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attributes

## Expected behavior

xstyled props should not change native attributes of html elements

**Comment by gregberge** [comment]
@berikiushi I think it is not too late to remove `size`, there is not lot of users on v2. I agree it should not overlap.
