### ISSUE TITLE
New built-in utility: textSize

### ISSUE THREAD

**Issue by AndrewPrifer** [gregberge/xstyled#178]
## 🚀 Feature Proposal

I propose a new builtin `textSize` utility, that combines font size and line height.

## Motivation

I love the inspirations xstyled 2 took from Tailwind, especially the new utility style props. One thing that I'm missing is Tailwind's combination of font size and line height, which makes an awful lot of sense. Unless you have very specific design needs, these two properties are always coupled.

## Example

`<x.div textSize="xl">...</x.div>` = `<x.div fontSize="xl" lineHeight="xl">...</x.div>`

## Pitch

xstyled 2 already has a lot of builtin utilities and a default theme, which is great! I think taking more inspiration from Tailwind can carve out a niche for xstyled among the dozens of low-level CSS-in-JS libraries by providing a more complete utility-based styling solution.

**Comment by AndrewPrifer** [comment]
Would be happy to try and open a pull request for this 🤟

**Comment by gregberge** [comment]
Hello @AndrewPrifer, I think it is better to be able to specify a `lineHeight` along a `fontSize` and use it in `fontSize` utility. [Tailwind does it](https://tailwindcss.com/docs/font-size#providing-a-default-line-height).

I think we could use an object in theme and detect it in `fontSize` utility:

```js
const theme = {
  fontSizes: {
    xs: { fontSize: '10px', lineHeight: 1.4, letterSpacing: '-0.2em' },
  }
}
```

What do you think?

**Comment by AndrewPrifer** [comment]
Good idea! Is there a downside to not having a separate text utility though? The default tailwind theme doesn't have default line heights for font sizes, preferring instead the text utility for specifying them together. I think one reason for that could be that it'd make the fontSize utility the single utility that applies two instead of one CSS property, which is a pretty huge exception. We could support both.

**Comment by gregberge** [comment]
@AndrewPrifer could you link me text utility in Tailwind?

**Comment by AndrewPrifer** [comment]
@gregberge sure, right at the top on this page: https://tailwindcss.com/docs/font-size

**Comment by AndrewPrifer** [comment]
Okay, I definitely misunderstood the TW docs, I thought that font size and text size were separate things. I still think however that if xstyled is going to apply both a font size and a line height property, it shouldn't be named `fontSize`, because it can be confusing. I think Tailwind made the right call not calling it `font-xs` etc.

**Comment by gregberge** [comment]
@AndrewPrifer yeah we should add `text` instead you are right.

**Comment by AndrewPrifer** [comment]
@gregberge one thing, I did some research and there is in fact one element, the svg element that supports a text attribute. Would you like it to be called `textSize` instead?

**Comment by JDansercoer** [comment]
Hey guys, would love to help look into this as well.

In all of the projects where I've used `xstyled` (or `styled-system` in some older projects before I stumbled upon this), I have always added a `Text` component that kind of does what is requested here. 

While I'm not 100% looking in the same direction as what the main topic of this request is, I do think we can combine efforts to create something that can be more widely used.

To chip in my current workflow: I always get my designs in Figma (which is quickly becoming the nr.1 design tool). In Figma, especially in bigger products or in designs where consistency is key, designers tend to work with [text styles](https://www.figma.com/best-practices/typography-systems-in-figma/). The results in "named" combinations for a lot of the font properties. An example output of text that has a text style applied to it:

```
/* Display / Semibold Heading 1 */
font-family: Silka;
font-style: normal;
font-weight: 600;
font-size: 160px;
line-height: 192px;
/* identical to box height, or 120% */
```

What I often end up doing, is creating a Text file that handles this, which enables me to "think more like a designer" and further close the gap between our mental models.

Below is a small excerpt of the Text component in my latest project. It's not super heavily optimized, but it does the trick. I'd love to think with you guys on how we maybe could incorporate something similar into xstyled.

```
import React from 'react';
import styled from 'styled-components';
import { typography, TypographyProps, space, SpaceProps } from '@xstyled/system';

const Wrapper = styled.div<{ ref }>`
  ${typography};
  ${space};
`;

const styles = {
  ...
  SemiboldHeading1: {
    fontSize: 9,
    fontWeight: 600,
    lineHeight: 1.25,
  },
  ...
};

export type Styling =
  ...
  | 'SemiboldHeading1'
  ...;

export interface TextProps extends TypographyProps, SpaceProps {
  styling: Styling | { xs: Styling; sm?: Styling; md?: Styling; lg?: Styling; xl?: Styling };
  forwardAs?: React.ElementType;
  dangerouslySetInnerHTML?: {
    __html: string;
  };
}

const Text: React.FC<TextProps> = React.forwardRef(
  ({ styling, color = 'primary.text', forwardAs, ...rest }, ref) => {
    let stylingProps;
    if (typeof styling === 'string') {
      stylingProps = styles[styling];
    } else {
      stylingProps = {
        fontSize: {},
        fontWeight: {},
        lineHeight: {},
      };
      Object.keys(styling).forEach((breakPoint) => {
        stylingProps.fontSize[breakPoint] = styles[styling[breakPoint]].fontSize;
        stylingProps.fontWeight[breakPoint] = styles[styling[breakPoint]].fontWeight;
        stylingProps.lineHeight[breakPoint] = styles[styling[breakPoint]].lineHeight;
      });
    }

    return (
      <Wrapper
        fontFamily="primary"
        color={color}
        {...stylingProps}
        {...rest}
        ref={ref}
        as={forwardAs}
      />
    );
  },
);

export default Text;
```

This then allows me to use the `Text` component as follows, automatically setting all the correct props for me to correspond with the text style used by the designer.

```
<Text styling="SemiboldHeading1">Hello world</Text>
```

**Comment by gregberge** [comment]
The text utility will allow to combine all typography properties into a single style. So it will be a perfect replacement for your component.

**Comment by AndrewPrifer** [comment]
@gregberge @JDansercoer  I fee like this is getting out of scope for the original intention of unifying properties related to text size. I believe letter spacing is already somewhat stretching it (Tailwind does it too so it is fine), but I think font family, style and weight would belong somewhere else.

I'm all for creating more utilities, but I think font size, line height and letter spacing are significantly more coupled than the rest of the properties, and that's what I'd like to target here with the `textSize` utility.

I propose that for that, a separate `textStyles` utility be created to bundle all typographic properties together, similarly to [what Chakra has](https://chakra-ui.com/docs/features/text-and-layer-styles), and leave this utility for size only, on the analogy of Tailwind's `text-{size}` utilities.

**Comment by gregberge** [comment]
- For the name, please use "text", [the attribute does not exist](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes), only a [`text` tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text) exists
- About the properties that it should support, for me it should support [all typographies properties](https://github.com/gregberge/xstyled/blob/master/packages/system/src/styles/typography.ts)

@AndrewPrifer You said Tailwind uses only `text-{size}` but it is not true, [`text-left` adjust the alignment for example](https://tailwindcss.com/docs/text-align).

xstyled provides a similar default theme as the Tailwind one, because Tailwind one is very good and allow to build a beautiful design easily. So in default theme, we will stick to the strategy and defines the utilities provided by Tailwind, example:

```js
const theme = {
  texts: {
    center: { textAlign: 'center' },
    lg: { fontSize: '1.125rem', lineHeight: '1.75rem' },
  }
}
```

But I think it is a good thing that users could use it to create all their text styles. We have the best of two worlds.

So about spec.: 

- `text` utility will have no fallback like `fontSize`. It will only read values from theme. 
- In the `texts` section of theme, the properties will follow their own sections, I mean `texts: { lg: { fontSize: 'lg' } }, fontSizes: { lg: '1.125rem' } }` should work fine

@AndrewPrifer is it OK for you, if it is I would like to say to you welcome as a xstyled maintainer!

**Comment by AndrewPrifer** [comment]
@gregberge sounds good! Sorry for the late reply, work got in the way! I'll get on it!

**Comment by AndrewPrifer** [comment]
> @AndrewPrifer You said Tailwind uses only `text-{size}` but it is not true, [`text-left` adjust the alignment for example](https://tailwindcss.com/docs/text-align).

I don't recall saying this, Tailwind of course has many other text utilities, my statement only regarded how the `text-{size}` utilities and the `fontSize` theme property allow for controlling all size related css properties together.

But I agree, a generic `text` utility that allows controlling all typographic properties would also make sense.

**Comment by gregberge** [comment]
Yeah, the philosophy of xstyled is giving power to user, everyone build his own design system with its own convention. That's why tokens are not prefixed by "$" for example, you are free to specify it or not. It will be the same for text utility, define size or more, as you want.

**Comment by agriffis** [comment]
@AndrewPrifer This is a really great idea! I've been fiddling with it and wanted to share in case it helps with your PR

```js
import {x as xx, style} from '@xstyled/styled-components'
import {typography} from '@xstyled/system'

const text = style({
  prop: 'text',
  themeGet: v => ({theme}) => typography({theme, ...theme.texts[v]}),
  cssProperty: v => v,
})

export const x = xx.extend(text)
```

This generalizes completely if you use `system` in place of `typography`, which may not be appropriate for this new built-in, but it makes me wonder a little bit. :thinking: 

For my own projects, I may personally use something like this:

```js
import {compose, space, typography} from '@xstyled/system'
import {omit} from '@xstyled/util'

const prose = style({
  prop: 'prose',
  themeGet: v => ({theme}) => compose(space, typography)({theme, ...theme.texts[v]}),
  cssProperty: v => v,
})

const ui = style({
  prop: 'ui',
  themeGet: v => ({theme}) => typography({theme, ...theme.texts[v]}),
  cssProperty: v => v,
})
```

so that I can apply the same set of typographic settings between prose with accompanying margins, and ui elements without.

**Comment by gregberge** [comment]
It will be part of v3, https://github.com/gregberge/xstyled/pull/228

**Comment by agriffis** [comment]
Catching up with Greg's latest changes, comparing what he did to what I had suggested above.

<table><tr><th>My solution (above)</th><th>Greg's solution (08369145be722607f213c5b43f6b23263e7ca1a1)</th></tr><tr><td>

```js
const text = style({
  prop: 'text',
  themeGet: v => ({theme}) => 
    typography({theme, ...theme.texts[v]}),
  cssProperty: v => v,
})
```

</td><td>

```js
const text = style({
  prop: 'text',
  key: 'texts',
  cssProperty: (value) => ({theme}) => 
    typography({...value, theme}),
})
```

</td></tr></table>

In both solutions, there is an extra layer of indirection through the theme:

* my solution: both lookups in `themeGet`, first is `theme.texts[v]`, second is `typography` passing `theme` as a prop
* Greg's solution: first is the default `themeGet` resolving `key`, second is `cssProperty` calling `typography`

Greg's solution was enabled by [this change](https://github.com/gregberge/xstyled/commit/66ac294eb7fa0760bf75b1ac679e9e964397c915) which enables `cssProperty` to do the theme lookup. Previously this was impossible, hence the hackiness of my approach with the identity function. 

Finally, closing the loop on my personal usage with the enhanced `cssProperty` (which is called `css` in v3), I will probably take this approach:

```js
import {x as xx, style} from '@xstyled/styled-components'
import {compose, space, typography} from '@xstyled/system'
import {omit} from '@xstyled/util'

/**
 * prose is like xstyled "text" but it also applies margins for space-after
 */
const prose = style({
  prop: 'prose',
  key: 'texts',
  css: (value) => ({theme}) => compose(space, typography)({...value, theme}),
})

export const x = xx.extend(prose)
```

With this approach, I have the xstyled-provided `text` for UI elements, and my own `prose` for full-flow typography. Both use values from `theme.texts` but the xstyled-provided `text` only applies `typography` so it will ignore margins specified there, whereas `prose` will apply them.
