### ISSUE TITLE
TypeScript w/ out-of-the-box defaultTheme + jsx attributes 

### ISSUE THREAD

**Issue by vincentbriglia** [gregberge/xstyled#180]
Hi, 

following the readme's and guides on how to set up xstyled with either styled components or emotion (but avoiding using the 'x' notation, we know you recommend this approach, but we want to avoid using the 'x' notation and keep the 'styled' notation) we are bumping into an issue with TypeScript that we cannot seem to solve. 

We aim to get the typed values from the defaultTheme, and in the future, from a custom theme, instead of the default css values. 

![image](https://user-images.githubusercontent.com/452811/105826824-77502500-5fc1-11eb-85bb-9965d03b164d.png)

when using the prop function notation we get the correct types, we also understand that the string interpolation method with `th` or hooks with `useTheme` or the "magic" notation does not have strong typing.

![image](https://user-images.githubusercontent.com/452811/105828911-fb0b1100-5fc3-11eb-90e0-facbc714c177.png)

we understand that https://github.com/gregberge/xstyled/issues/163 `but I was wondering if the prop notation were at least supposed to infer possible values from the theme? from the typings it seems that this is possible, or at least intended, but we cannot figure out how to make xstyled infer them from the SystemProps' defaultTheme, instead of from the CSS default props.

**Comment by vincentbriglia** [comment]
Silly, for anyone bumping into this issue, when you work using the styled notation, make sure to extend your component from the `SystemProps<Theme>` or `SystemProps<DefaultTheme>` interface, where `Theme` or `DefaultTheme` are your custom emotion or styled components theme or the default theme respectively.

**Comment by gregberge** [comment]
By following [TypeScript guide](https://xstyled.dev/docs/typescript/) everything should work fine with v3.
