### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Reckvy** [gregberge/xstyled#187]
Hi, does it make sense to create namespaces with less utilities? Will it be more performant than `x`? Sorry if this has been already asked, haven't found

**Comment by gregberge** [comment]
Hello @Reckvy, not it will no be more performant. However it will be lighter since you will include less utilities in your bundle.

**Comment by gregberge** [comment]
I should mention it in the docs.

**Comment by Reckvy** [comment]
@gregberge thanks!
