### ISSUE TITLE
Shorthand for breakpoints

### ISSUE THREAD

**Issue by agriffis** [gregberge/xstyled#189]
## 🚀 Feature Proposal

Handle media queries more elegantly in styled components, for example `@up(md) { ... }` instead of ``${up('md', css`...`)}``

## Motivation

xstyled makes theming in styled components easy and beautiful, but breakpoints are still unwieldy.

## Example

The xstyled-powered `styled` is awesome, because you can write familiar CSS rules that reference theme values directly. But it gets ugly when you have to reference breakpoints:

```jsx
const Box = styled.div`
  width: 200px;
  height: 200px;
  ${up(
    'md',
    css`
      height: 300px;
    `,
  )}
`
```

It would be nice to recognize the common media-query and replace it automatically:

```jsx
const Box = styled.div`
  width: 200px;
  height: 200px;
  @media (min-width: md) {
    height: 300px;
  }
`
```

Alternatively, some kind of shorthand for up and down:

```jsx
const Box = styled.div`
  width: 200px;
  height: 200px;
  @up(md) {
    height: 300px;
  }
`
```

## Pitch

My guess is that this should be a more generic at-rule transformer that could be extended to other uses over time, but I'm curious what other people think... (not really a pitch, more an inquiry)

**Comment by gregberge** [comment]
Hello @agriffis, I was thinking about it! I don't want to re-invent a language, so we should support:

```js
@media (min-width: md)
```

not

```js
@up(md)
```

**Comment by gregberge** [comment]
I am up for it, but it should have a very very small impact on perf.

**Comment by agriffis** [comment]
FYI I'm making good progress on this and will open a PR for discussion soon

**Comment by agriffis** [comment]
PR is #194

**Comment by gregberge** [comment]
Done in #194
