### ISSUE TITLE
xstyled v2 equivalent of styled-components' styled(ExistingComponent)

### ISSUE THREAD

**Issue by jbmusso** [gregberge/xstyled#191]
Hi @gregberge, thanks for xstyled v2 which is becoming our standard library here.

I may have slightly misunderstood an aspect of your library but I'm trying to style a few existing components with xstyled. The way I do it with styled-components is calling `styled(ExistingComponent)`, but I was looking for an API using v2 styles-as-props.

What would be the recommended approach please? I apologize in advance if I missed that when searching in the documentation or other issues:
* https://xstyled.dev/docs/migrate-from-styled-components/
* https://xstyled.dev/docs/enhanced-styled-components/

**Comment by gregberge** [comment]
Hello @jbmusso,

I am sorry because it is not part of the documentation. But it is easy to do!

Several methods:

```
styled.box``.withComponent(Existing)

styled(Existing)`
  ${system}
`

(props) => <x.div as={Existing} {...props} />
```

All of these methods will give you a system props ready component.

**Comment by jbmusso** [comment]
Thanks! I confirm that these solutions work for us.
