### ISSUE TITLE
The css `float` property is not supported by xstyled

### ISSUE THREAD

**Issue by jsfez** [gregberge/xstyled#192]
## 🐛 Bug Report

The css `float` property is not supported by xstyled

## To Reproduce

```
import React from "react";
import {
  x,
  defaultTheme,
  ThemeProvider,
  Preflight
} from "@xstyled/styled-components";

export default function App() {
  return (
    <ThemeProvider theme={defaultTheme}>
      <Preflight />
      <x.div backgroundColor="red">
        container
        <x.span backgroundColor="blue" width={30} float="right">
          hey!
        </x.span>
      </x.div>
    </ThemeProvider>
  );
}
```

## Expected behavior
Hey span should be on the right of his container.

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

https://codesandbox.io/s/xstyled-v2-playground-forked-bgf0c

**Comment by agriffis** [comment]
@jsfez I don't know @gregberge's intention for this, but in the meantime, [you could add it for your own project](https://xstyled.dev/docs/adding-new-utilities/):

```js
import {x as xx, styled} from "@xstyled/styled-components"

const float = style({
  prop: 'float',
})

export const x = xx.extend(float)
```

**Comment by gregberge** [comment]
@agriffis I think it should be supported out of the box.
