### ISSUE TITLE
TypeScript autocompletion not always working

### ISSUE THREAD

**Issue by areknawo** [gregberge/xstyled#193]
## 🐛 Bug Report

First off - love the tool! Good idea, well-executed, and nicely documented!

I'm creating this issue because I've noticed that TypeScript intellisense/autocompletion doesn't always work the way it should be.
The issues that I've identified so far:
1. no default theme autocompletion for size-related props (`h`, `w`, etc.)
2. no breakpoints autocompletion for any prop
3. no `x.` autocompletion for `/emotion` package
4. `x.extend()` return `any`

As for potential solutions, I've noticed the first two can be solved by customizing the `DefaultTheme` type, although it should work "out-of-the-box" for the default theme.
1. Can be solved by removing or setting `1` and `0.5` theme's `sizes` props to a value different than the default `undefined`. I know it's there from JS to fix the ["fluid range conflict"](https://xstyled.dev/docs/height/#scaled-height), but I think it can be fixed in a type-only manner, without affecting the JS code.
2. Can be solved by setting the theme's `breakpoints` prop to an empty object. It's caused by the possibly-wrong definition of `Breakpoints` type:

```typescript
  export type Breakpoints<TTheme extends ITheme> = TTheme extends {
    breakpoints: IBreakpoints
  }
    ? TTheme['screens']
    : Record<string, unknown>
  ```
  The `breakpoints` prop in the `extends` check should be replaced by `screens`, IMHO.

3 and 4 I haven't investigated further.

## To Reproduce

Trigger autocompletion in Playground (Ctrl+Space) while writing e.g. `h` prop, or any prop for breakpoints.

## Expected behavior

TypeScript autocompletion should work as expected, as it provides a lot of value and a huge productivity boost for xstyled users.

**Comment by gregberge** [comment]
Hello @areknawo, unfortunately I am not a TypeScript expert and I don't use it every day to be honest. This was my first big TypeScript project. Every improvement is welcome, feel free to fix things in a PR.

**Comment by jgirardet** [comment]
Not the same thing but somehow related, ff someone is coming here with autocompletion trouble using
`import { x } from "@xstyled/styled-components";`
 use `yarn add @types/styled-components`
very simple but I spent time on it.

**Comment by gregberge** [comment]
I tested it and it works fine, please follow carefully this guide: https://xstyled.dev/docs/typescript/#use-typescript-with-styled-components
