### ISSUE TITLE
Themeable Durations

### ISSUE THREAD

**Issue by ivoilic** [gregberge/xstyled#198]
## 🚀 Feature Proposal

`durations` should be included in the theme, accessible using `getDuration`.

## Motivation

Currently all other properties of transitions can be included in a theme. Duration is a nice value to have standardized.

## Example

```jsx
<x.button transition transitionDuration="valueFromTheme" >
  Hover me
</x.button>
```

## Pitch

I see no reason why this property which is already so well implemented shouldn't also be available for theming! At the very least it should be noted in the docs that this isn't currently possible.

**Comment by Makskow** [comment]
Absolutely agreed. In addition to the style prop pattern, it should also be possible with the `th` helper when using `styled` pattern, for example:
```
const Div = styled.div`
  transition: all ${th.transitionDuration('fast')} ease-in;
`
```
Or even with xStyled's magic interpolation:
```
const Div = styled.div`
  transition-duration: fast;
`
```

Given that both patterns are possible with `transitionProperty`, it would be awesome to have the same option for `transitionDuration`!

**Comment by gregberge** [comment]
@ivoilic @Makskow yeah I think it would be a good addition.
