### ISSUE TITLE
Shortened min/max sizing props

### ISSUE THREAD

**Issue by Makskow** [gregberge/xstyled#199]
## 🚀 Feature Proposal

Sizing props `maxHeight`, `maxWidth`, `minHeight`, `minWidth` should have a shortened prop name variant, in addition to the regular one.

I can try making a PR if you'd be ok with these changes.

## Motivation

I saw that you switched to 'h' for height and 'w' for width props in v2. In those particular cases I like the shortened version, as it removes some verbosity. I think it would be good to have that option for other sizing props as well.

## Example

```
export const maxHeight = style({
  prop: ['maxHeight', 'maxH'],
  cssProperty: 'maxHeight',
  themeGet: getSize
})
```

Then

```
<x.div maxH={8} h={32} />

<x.div minW={8} w={32} />
```

## Pitch

This change achieves 3 things:
- Makes those properties consistent with height and width prop name changes in v2
- Makes those properties nicer to use
- Allows more choice without breaking the original name variants

**Comment by gregberge** [comment]
Hello @Makskow, I was wondering about it. Since users (you) are asking for it, I think I will add it.
