### ISSUE TITLE
column-gap / row-gap not using theme.space values

### ISSUE THREAD

**Issue by P1X3L** [gregberge/xstyled#200]
## 🐛 Bug Report

When I try to use `column-gap` or `row-gap` css properties with values coming from `theme.space` keys, it does not work.

It works correctly when I use these properties as style props though.

## To Reproduce

https://codesandbox.io/s/xstyled-v2-playground-forked-column-gap-row-gap-issue-9ridf

## Expected behavior

I expect `column-gap` and `row-gap` to be able to get values from `theme.space` when used in styled-components.

**Comment by gregberge** [comment]
Hello @P1X3L, I will add it as soon as I have a moment.

**Comment by P1X3L** [comment]
Thanks @gregberge 👍
