### ISSUE TITLE
Responsive Props

### ISSUE THREAD

**Issue by ivoilic** [gregberge/xstyled#201]
## 💬 Questions and Help

Sort of a question/suggestion:

xstyled's responsive system is excellent and works well out of the box!
It would be really great if whatever utility function that parses props and determines which value to use based on the breakpoint could be exported (if it isn't already) and documented.
This would allow for the creation of custom props that are responsive in the exact same manner as the xstyled utilities without the need for a seperate custom utility function.

If this utility function is already exported then can someone point it out and provide information on how to make use of it?

**Comment by gregberge** [comment]
Hello @ivoilic, you are probably looking for [`useBreakpoints`](https://xstyled.dev/docs/hooks/#usebreakpoints).
