### ISSUE TITLE
options argument is not passed into emotion styled function

### ISSUE THREAD

**Issue by macocha** [gregberge/xstyled#202]
## 🐛 Bug Report

As seen here: https://github.com/gregberge/xstyled/blob/9cec90b9574162148b5e4cbd7b8727d3e12ac22f/packages/emotion/src/styled.ts#L37
Original emotion styled is called only with `component` argument, while the underlying library `styled`, can also take an additional options argument used mostly with `shouldForwardProp`. 

## To Reproduce

Following code is not working as expected, `isUnderlined` prop is still being pushed into the `RouterLink` component:
```
import styled from "@xstyled/emotion";

export const Link = styled(RouterLink, {
  shouldForwardProp: (propName) => propName !== "isUnderlined",
})<LinkProps>`
  color: link.text;
  text-decoration: ${(props) =>
    props.isUnderlined === false ? "none" : "underlined"};
`;
```

## Expected behavior

Changing the import to direct import from emotion fixes the behaviour, although obviously it loses the access to theme, so needs to be worked around using the `th` helper.

```
import styled from "@emotion/styled";

export const Link = styled(RouterLink, {
  shouldForwardProp: (propName) => propName !== "isUnderlined",
})<LinkProps>`
  color: ${th.color("link.text")};
  text-decoration: ${(props) =>
    props.isUnderlined === false ? "none" : "underlined"};
`;
```

**Comment by gregberge** [comment]
Hello @macocha, thanks for reporting, I will investigate it as soon as I have a moment.
