### ISSUE TITLE
[TypeScript] Typing issue when spreading props on html element (.e.g. div)

### ISSUE THREAD

**Issue by NKBelousov** [gregberge/xstyled#203]
## 🐛 Bug Report

I get typing error for basic html attributes when spreading props on `x.*` elements. Honestly I don't know if I'm using it wrong or there is an internal problem, so any suggestion is welcome.

## To Reproduce

There is a sample repository to inspect the issue down below.
Notice that there is a typing error for `color` prop (`Type 'number & {}' is not assignable to type 'string'.)

## Expected behavior

It should be okay to spread props

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/aged-darkness-pgirn

**Comment by gregberge** [comment]
Hello @NKBelousov, your typing was wrong. You should use `React.ComponentProps` helper: https://codesandbox.io/s/sparkling-field-hg6ec

**Comment by NKBelousov** [comment]
@gregberge I see, thanks a lot :)

**Comment by NKBelousov** [comment]
@gregberge actually I think it would be cool to add this information to the docs, do you mind if I open PR for that?

**Comment by gregberge** [comment]
> @gregberge actually I think it would be cool to add this information to the docs, do you mind if I open PR for that?

Yeah feel free to complete it!

**Comment by vincent-vade** [comment]
Hi,

After using this helper types are valid but autocompletion isn't working like usually with x.* 

@gregberge do u have a suggestion about that ?

ty

**Comment by gregberge** [comment]
@vincent-vade no sorry, as I said, I am not a real TypeScript user. I write library in TypeScript but does not use it in my real project (waste of time 🤗).
