### ISSUE TITLE
Typescript docs

### ISSUE THREAD

**Issue by incompletude** [gregberge/xstyled#230]
It would be nice to have better docs for typescript users.

I think currently this is the only page related to typescript:

https://xstyled.dev/docs/typescript/

@gregberge you need a beer bro.

**Comment by gregberge** [comment]
Yeah it is a not very complete, and TypeScript is so difficult! Do you have one for me? 😅

**Comment by incompletude** [comment]
> Yeah it is a not very complete, and TypeScript is so difficult! Do you have one for me? 😅

For me, unfortunately, it is. :(

Does your library need funding? I work for a medium-size company and we fund a few projects.

**Comment by gregberge** [comment]
Thanks for the beer! Yeah I always need fund, i would be happy to take some days to work on it!

**Comment by incompletude** [comment]
> Thanks for the beer! Yeah I always need fund, i would be happy to take some days to work on it!

We are considering adopting react + typescript + xstyled, but I still have a lot of convincing to do. I think it is currently the best way to achieve consistent design across multiple projects. (I have built pocs with theme-ui, chackra-ui and styled system). If you could help me make my generic heading work it would be great. :)

**Comment by gregberge** [comment]
@incompletude `// @ts-ignore` is your friend, you know only the external interface is really important. If your code work, my advice is to not try harder. You will fix it when you will acquire enough TypeScript knowledge.

**Comment by incompletude** [comment]
@gregberge

I just decided to drop this idea and follow other alternatives. It is never a good sign when a maintainer is arrogant, ironic, and answer questions using blame. I hope the repo grows because it deserves better governance.

Best,

**Comment by gregberge** [comment]
@incompletude it was not arrogant or ironic at all. Check xstyled code, there is lot of `// @ts-ignore` in internals. It doesn't make any sense to waste time on typing internal of a method if it works.

**Comment by incompletude** [comment]
> @incompletude it was not arrogant or ironic at all. Check xstyled code, there is lot of `// @ts-ignore` in internals. It doesn't make any sense to waste time on typing internal of a method if it works.

I was not mentioning this answer, but a few others. Thx anyways.

**Comment by gregberge** [comment]
Good luck then!
