### ISSUE TITLE
New variant syntax?

### ISSUE THREAD

**Issue by incompletude** [gregberge/xstyled#238]
I read that the variant utility was dropped in favor of x.* syntax. How would one write button variants using the new syntax? I couldn't find any examples.

**Comment by gregberge** [comment]
> I read that the variant utility was dropped in favor of x.* syntax. How would one write button variants using the new syntax? I couldn't find any examples.

The example is in the doc.

**Comment by incompletude** [comment]
Since the docs doesn't have a search, and you already know where it is, it would be nice if you posted the link along with your answer.

**Comment by gregberge** [comment]
The doc has a search on desktop.

**Comment by gregberge** [comment]
@incompletude you should avoid considering open source maintainer like a kind bot that will answer all your questions. Most of maintainers do it on their free time. I answered on my mobile, quickly. I am sorry to not have taken time to leave my daughter alone, take my Macbook, look for the example in the code and copy paste it to avoid you a search in the docs. Very sorry my lord.
