### ISSUE TITLE
How to use emotion's autolabel with xstyled?

### ISSUE THREAD

**Issue by maxmedina05** [gregberge/xstyled#239]
## 💬 Questions and Help

How can you enable autolabels when using xstyled with emotion?

Without xstyled it would simply work by just adding the @emotion/plugin to the .babelrc file. I thought it would also work if I would add the @xstyled/babel-preset-emotion-css-prop to my .babelrc which is also using the emotion/plugin but I still can't see the labels on the class. Am I missing something?

**Current**
![image](https://user-images.githubusercontent.com/6037236/114666984-3386d500-9cff-11eb-9265-3a423bcc673b.png)

**Expected**
![image](https://user-images.githubusercontent.com/6037236/114667567-e48d6f80-9cff-11eb-995b-9c5659939c24.png)

I made a [sandbox ](https://codesandbox.io/s/thirsty-margulis-z1qfj?file=/sandbox.config.json)if anyone wants to help me

**Comment by agriffis** [comment]
I don't use emotion, but I think you need to set the `importMap`

https://github.com/emotion-js/emotion/tree/main/packages/babel-plugin#importmap

**Comment by gregberge** [comment]
@maxmedina05 if it fixes it for you could you please make a PR in documentation or just give the solution here, for Styled Components it is documented, but for emotion not.

**Comment by maxmedina05** [comment]
> @maxmedina05 if it fixes it for you could you please make a PR in documentation or just give the solution here, for Styled Components it is documented, but for emotion not.

I'm don't really understand how make this importMap work with xstyled but if I manage to get it working I will make a PR

**Comment by maxmedina05** [comment]
I managed to make it work like this.

```json
{
  "presets": [
    [
      "next/babel",
      {
        "@babel/react": {
          "runtime": "automatic",
          "importSource": "@emotion/react"
        },
      }
    ]
  ],
  "plugins": [
    [
      "@emotion/babel-plugin",
      {
        "importMap": {
          "@xstyled/emotion": {
            "default": {
              "canonicalImport": ["@emotion/styled", "default"]
            }
          }
        }
      }
    ]
  ]
}
```

![image](https://user-images.githubusercontent.com/6037236/114757156-cbb2a780-9d5b-11eb-83e5-98a467c4dd93.png)

It didn't work with the @xstyled/babel-preset-emotion-css-prop

**Comment by maxmedina05** [comment]
shouldn't it also work with @xstyled/babel-preset-emotion-css-prop since its calling the emotion-babel-plugin? its not passing "importMap" to the emotion-babel-plugin

 @gregberge 

https://github.com/gregberge/xstyled/blob/main/packages/babel-preset-emotion-css-prop/src/index.ts#L44

**Comment by maxmedina05** [comment]
I noticed that using my approach from earlier is just working partially. Maybe I'm missing something in the options of the babel-plugin.

For example, I make a styled component like this:

```js
const StyledContainer = styled(x.div)({
  padding: "16px",
  backgroundColor: "emerald-500"
});
```

babel would generate something like this:
```jsx
var StyledContainer = ( /*#__PURE__*/0, _emotion["default"])(_emotion.x.div, process.env.NODE_ENV === "production" ? {
  target: "e1ip49im0"
} : {
  target: "e1ip49im0",
  label: "StyledContainer"
})(process.env.NODE_ENV === "production" ? {
  name: "1a9a87p",
  styles: "padding:16px;background-color:emerald-500"
} : {
  name: "1a9a87p",
  styles: "padding:16px;background-color:emerald-500",
  map: "/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL3BhZ2VzL2luZGV4LnRzeCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFLd0IiLCJmaWxlIjoiLi4vcGFnZXMvaW5kZXgudHN4Iiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IExpbmsgZnJvbSBcIm5leHQvbGlua1wiO1xuaW1wb3J0IFNlYXJjaCBmcm9tIFwiLi9zZWFyY2hcIjtcblxuaW1wb3J0IHN0eWxlZCwgeyB4IH0gZnJvbSBcIkB4c3R5bGVkL2Vtb3Rpb25cIjtcblxuY29uc3QgU3R5bGVkQ29udGFpbmVyID0gc3R5bGVkKHguZGl2KSh7XG4gIHBhZGRpbmc6IFwiMTZweFwiLFxuICBiYWNrZ3JvdW5kQ29sb3I6IFwiZW1lcmFsZC01MDBcIlxufSk7XG5cbmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIEluZGV4UGFnZSgpIHtcbiAgcmV0dXJuIChcbiAgICA8U3R5bGVkQ29udGFpbmVyPlxuICAgICAgSGVsbG8gV29ybGQue1wiIFwifVxuICAgICAgPExpbmsgaHJlZj1cIi9hYm91dFwiPlxuICAgICAgICA8YT5BYm91dDwvYT5cbiAgICAgIDwvTGluaz5cbiAgICAgIDxTZWFyY2ggLz5cbiAgICA8L1N0eWxlZENvbnRhaW5lcj5cbiAgKTtcbn1cbiJdfQ== */",
  toString: _EMOTION_STRINGIFIED_CSS_ERROR__
});
```

It's just passing the styles directly to emotion in a styles property but also parsed and bypassing xstyles.

Any ideas? @agriffis @gregberge 

Btw my PR from earlier in the docs could be misleading since it is not working 100% out of the box.

**Comment by learnitmyway** [comment]
Has there been any progress on this? Is it documented somewhere?

Thanks
