### ISSUE TITLE
cssProperty and pseudo-element

### ISSUE THREAD

**Issue by iManu** [gregberge/xstyled#251]
## 💬 Questions and Help

Hello Greg,

As we use xstyled in a new project, we're glad to perform with the tool :)

We trying using pseudo element like `::before` in the way [it is described in the doc](https://xstyled.dev/docs/adding-new-utilities/#generate-arbitrary-style), but we cannot make it work.

The code of utilities :

```js
import { style, x } from '@xstyled/styled-components'

export const pseudoEl = x.extend(
  style({
    prop: 'pseudoEl',
    cssProperty: () => ({
      '&::after': {
        content: 'TEST',
        fontSize: '16px',
        position: 'absolute',
        zIndex: 1,
        top: 0,
        left: 0,
      },
    }),
  }),
)
```

then in component `import { pseudoEl as p } from 'utilities'`

and in jsx `<p.div pseudoEl>Expect ::after in DOM</p.div>`

but nothing happens, what is wrong with our code ?

![Capture d’écran 2021-04-27 à 11 18 14](https://user-images.githubusercontent.com/341803/116218445-d2252400-a74a-11eb-9ee7-ff8c150c766c.png)

**Comment by gregberge** [comment]
Hello @iManu, it is a styled-components problem, content must be `content: '"TEST"'` with double quotes. https://twitter.com/peduarte/status/1361369526613475335
