### ISSUE TITLE
Color prop responsive type

### ISSUE THREAD

**Issue by AlfonzAlfonz** [gregberge/xstyled#257]
## 🐛 Bug Report

Color prop type definition from xstyled interferes with react definition, which removes responsive definition from types. I would gladly fix this if you tell me where is the problem.

## To Reproduce

```tsx
  <x.div color={{ _: "red" }}>Test</x.div>
```

## Expected behavior

Typescript should allow this, otherwise, it works fine.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/xstyled-color-type-error-b4fw2

**Comment by gregberge** [comment]
Fixed in v3, please be patient!

**Comment by gregberge** [comment]
Fixed in v3.

**Comment by AlfonzAlfonz** [comment]
Unfortunately, it seems that there are still problems with the type of color prop.

Updated sandbox example: https://codesandbox.io/s/xstyled-color-type-error-forked-v3kz2?file=/src/App.tsx

**Comment by AlfonzAlfonz** [comment]
I'm sorry but I was unable reopen this issue, should I open a new one? @gregberge
