### ISSUE TITLE
How can i add a custom prop to styled divBox ?

### ISSUE THREAD

**Issue by joetifa2003** [gregberge/xstyled#259]
### How can i add a custom prop to styled divBox ?

I want to add a gutter prop to a styled divBox to add negative margin and padding for children (how can i add custom props other than p, m, h, w, etc...).

My current sloution is like this
![image](https://user-images.githubusercontent.com/62658783/118384565-4abf2800-b607-11eb-9cf3-de1167775b66.png)

Using the margin prop for the children padding.

**Comment by gregberge** [comment]
Hello @joetifa2003, [space-between](https://xstyled.dev/docs/space-between/#space-between) should work for your use case. Else my advice is to use `margin` utility directly at the position you want:

```js
import { row, margin } from '@xstyled/system'

const Row = styled.divBox`
  ${row.apply({ row: true })}
  > div {
    ${margin}
  }
`
