### ISSUE TITLE
Have v3 plan for support IE11 (ES5 cjs dist)? 

### ISSUE THREAD

**Issue by strozw** [gregberge/xstyled#263]
## 💬 Q: About support for IE11

I'm using v2 in my project, this project support IE11.

Would like to use v3 in this project if possible.

However, the esbuild that v3 uses for build does not support es5 output.

So I'm currently testing if v3 csj dist can be transpiled with webpack & babel with the following workaround to see if it works in IE11.

have you advice on the use v3 in IE11?

### workaroud in webpack.config.ts

```ts
export default {
  ︙
  resolve: {
   alias: {
     '@xstyled/util': '@xstyled/util/dist/index.js',
     '@xstyled/core': '@xstyled/core/dist/index.js',
     '@xstyled/system': '@xstyled/system/dist/index.js',
     '@xstyled/styled-components': '@xstyled/styled-components/dist/index.js',
   }
  },
  module: [
    ︙
    {
      test: /\.js$/,
      include: [
        /node_modules\/@xstyled\/util/,
        /node_modules\/@xstyled\/core/,
        /node_modules\/@xstyled\/system/,
        /node_modules\/@xstyled\/styled-components/,
      ],
      use: [
        {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                require.resolve('@babel/preset-env'),
                { modules: 'commonjs' },
              ],
            ],
            cacheDirectory: true,
          },
        },
      ],
    }
  ]
}
```

**Comment by gregberge** [comment]
Hi @strozw, IE 11 is 8 years old and Microsoft will end support in 1 year, so no we will never support it with xstyled.

**Comment by strozw** [comment]
Hi @gregberge, thanks answer for my question.

>  IE 11 is 8 years old and Microsoft will end support in 1 year, so no we will never support it with xstyled.

Ok, That's right. 😁 

However, the performance of type checking in xstyled v3 is so attractive that I would like to explore making it available in IE11. 🤔 

Perhaps the obstacle to transpiling to ES5 and using it in IE11 is the css variable.
However, it seems that the place where css variable is used in xstyled v3 is only the color mode feature as in v2.
Therefore, if do not use the color mode switching, it is judged that can use it without problems.

Fortunately, my project doesn't use color mode, so I decided to use es5 transpiled dist by babel. 

Thanks for your great work 👍🏻
