### ISSUE TITLE
Add `overscrollBehaviorX` and `overscrollBehaviorY` props

### ISSUE THREAD

**Issue by SpencerDuball** [gregberge/xstyled#268]
## 🚀 Feature Proposal

Adding the props `overscrollBehaviorX` and `overscrollBehaviorY`.

## Motivation

Using the`overscrollBehaviorX` would be a good addition, while working on a carousel component I want to scroll to the end of a div, but on a touchpad scrolling to the end will trigger the "forward" and "back" buttons of a web browser such as chrome. Using just `overscrollBehavior` prevents scrolling vertically and causes a bad user experience.

## Example

This would be used just as `overscrollBehavior`. Actually, `overscroll-behavior-x` and `overscroll-behavior-y` are what `overscrollBehavior` gets computed as on the browser.

## Pitch

This is a feature that has the same availability as `overscrollBehavior` across browsers, and `overscrollBehavior` is supported. This would provide a fine-grained API that would be useful for UX.

**Comment by gregberge** [comment]
Since xstyled is now [fully extendable](https://xstyled.dev/docs/adding-new-utilities/), these feature will not be part of the core, it is too specific.
