### ISSUE TITLE
Yarn add Breaks with 3.0.0 works with 2.5.0

### ISSUE THREAD

**Issue by msimonc** [gregberge/xstyled#270]
Thanks for this project!!

I happened to be doing a complete package reinstall on my project and this came up:

node_modules/@xstyled/system/dist/index.js:336
    const rootFontSize = props?.theme?.settings?.rootFontSize ?? void 0;

Breaks in 3.0.0 gives me no errors in 2.5.0

FYI I'm using @welcome UI components.

**Comment by gregberge** [comment]
Fixed in v3.0.1.
