### ISSUE TITLE
Scale object in theme

### ISSUE THREAD

**Issue by indiejoseph** [gregberge/xstyled#283]
## 💬 Questions and Help

I wonder is there any way to do responsive scale in theme object, like how styled-system does https://styled-system.com/theme-specification#scale-objects.

```js
{
...
  texts: {
    heading: {
      fontSize: { sx: '14px', md: '16px', lg: '18px' }, // does't work with xstyled
      // fontSize: ['14px', '16px', '18px'], with styled-system
    },
  }

<x.p text="heading" />
```

Thanks!

**Comment by gregberge** [comment]
Actually that's not the way it works but I will consider it! Thanks.

**Comment by indiejoseph** [comment]
Thanks! I wonder how did you handle it?

or something like:
```
<x.p text={{ xs: 'heading1', lg: 'heading2' }} />
```

**Comment by gregberge** [comment]
> <x.p text={{ xs: 'heading1', lg: 'heading2' }} />

yeah
