### ISSUE TITLE
Is it possible to have group-hover, group-focus styles like the ones found in tailwind ?

### ISSUE THREAD

**Issue by joseDaKing** [gregberge/xstyled#290]
Is it possible to have group-hover, group-focus styles like the ones found in tailwindcss?

**Comment by gregberge** [comment]
Yeah, you can add a custom state:

```js
const theme = {
  ...defaultTheme,
  states: {
    ...defaultTheme.states,
    'group-hover': '.group:hover &',
    'group-focus': '.group:focus &',
}
```

Then add a `className="group"` on the group, and use `group-hover` state on children. Do you see what I mean?
