### ISSUE TITLE
VSCode code completion requires type definitions for styled-components

### ISSUE THREAD

**Issue by ibejoeb** [gregberge/xstyled#309]
It appears that Visual Studio Code can't do code completion/intellisense for `x.*` element attributes without adding `@types/styled-components`. It might be worth noting in the TypeScript section of the docs. I'm happy to do it; just need a little guidance on the process.

**Comment by gregberge** [comment]
Since you have to install `styled-components` when you use `@xstyled/styled-components` it seems obvious that if you use TypeScript you also have to install `@types/styled-components` since `styled-components` does not have included typings.
