### ISSUE TITLE
Linaria

### ISSUE THREAD

**Issue by ivanbanov** [gregberge/xstyled#314]
## 💬 Questions and Help

Quick question, is there any interest in supporting [Linaria](https://github.com/callstack/linaria)? Would a PR be welcome?

**Comment by gregberge** [comment]
Hello @ivanbanov yeah interested to see what's the result with Linaria.

**Comment by ivanbanov** [comment]
My team moved away from Linaria, we are not expecting to implement it anymore.
Therefore Im closing this issue :)
