### ISSUE TITLE
Add support for margin-inline-* properties

### ISSUE THREAD

**Issue by probablyup** [gregberge/xstyled#325]
## 🚀 Feature Proposal

CSS has added [some style rules](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start) for adding margin based on logical block position in bidi scenarios.

Would be good to get this implemented into xstyled for both normal `styled` composition and as a prop.

**Comment by agriffis** [comment]
It's a new day, but still, for historical perspective see #210

**Comment by probablyup** [comment]
Fair enough! Most websites probably won't need this so happy to defer to extension to support more enterprise-y use cases.

**Comment by agriffis** [comment]
@probablyup To be clear, I wasn't trying to shut you down. My guess is this could be revisited if it makes sense. Just rang a bell in my mind, I knew I'd seen this before.

**Comment by gregberge** [comment]
Yeah I think we could propose an official i18n extension that supports this, but it does not make sense in the core.
