### ISSUE TITLE
How can I get typescript type inference for the theme values

### ISSUE THREAD

**Issue by joseDaKing** [gregberge/xstyled#337]
## 💬 Questions and Help

How can I get typescript type inference for the theme values?

For example, when I try to use the color prop I don't get the type inference for the color values defined in the theme and also in the CSS values

```ts
<x.div color=""/>
```

**Comment by jguddas** [comment]
Take a look at the docs https://xstyled.dev/docs/typescript/#use-typescript-with-styled-components and this [playground](https://www.typescriptlang.org/play?ssl=20&ssc=33&pln=1&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoUSWOAbzgA84BfObXAgAQYGcYBPADZIAJgHo+Q0QFo0uSADskCmDzLkKchXzgwAFkhBI4AXjoU4cOYOg8AXOfKXLSBinDCH+AEaCArkjqlswUIRrkAmDGAIJgYAAqBkamuvxREJi6SUgUFCJIaIIoRHAgECJ+wly8AsLiPPx8hviOLgzU8MAqSFCY6MaJhsauMMoiPHCxCdl0YWF5BUUlZRVV+JJ1svIQSipqrXCuHXBdo739cAAiSH2VMIPJI2MTUw-GtHO55EfQ8Pm3gngAB4GAA6ETAABuVggNigJgARAixAA+IA).

If you want to customize what color types are possible, have a look at this [playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wFgAoUSWOAbzjSJRiQGEBndgGjnYE92LEDzS5I7JDwDKAoQAUcYabKQgFEMNzgAVABarJcACZJMKAK4AbGHoNwAvnGy4CAAQAegvpaRGA9F4+RgC0ouAQAHZIETDsZOQUfn68KiAAdLEUwDFIUGZoSHAygqpwSO4sEUbsRanqmnQUcAwQltAA-ABctSVqigA8ANZIfBCYOvogSADa+KJtUHEAujy2UwB8FPYUFOXU8KIRgnRw7g5wALwMTCwc7AAUYeJI-cVC6-f8vQCU3zvkSTgMEmSAy7F27n2LSO8GBdiutCavBgzCQ7G6JjMVhsILSglR3CR82g6Ma5GazXKKHAPm6+AARpZzEh4s1tuR2YlkoFfGkjGCKDA+GBCgBBMBgNaFK5CkVjIEg-4mNCWFBEOAgCBGKyFfAeHn+L5CfBkymQ6DwbIsPLoQpSsoVaLVODiyUgujsznkZWq9Wa7U+AgG0JiSLRWImxHkh1Qq25fKFAAipgs1nt5Uqztd9tonv+gKpNNBmXIewtxhT2Lg-XcfOAADcWgsLgAiFt+dZAA).
