### ISSUE TITLE
Attempted import error: `createColorModeProvider` is not exported from `@xstyled/core`.

### ISSUE THREAD

**Issue by patrikmasiar** [gregberge/xstyled#376]
## 🐛 Bug Report
In my React application, I have installed:
```
 "@xstyled/core": "^3.6.0",
"@xstyled/styled-components": "^3.6.0",
"styled-components": "^5.3.5"
```

and I got this error:
<img width="786" alt="Snímka obrazovky 2022-07-27 o 9 24 18" src="https://user-images.githubusercontent.com/8200096/181187376-dd45a8c2-0b95-41e2-a9d0-18843e257622.png">

## To Reproduce
Install the same versions of packages in the React application and run the project

**Comment by likewerealive** [comment]
I ran into the same issue as this. It seems to be when using xstyled v3 with  react v17 / react-scripts v4. It works all fine with react v18

**Comment by gregberge** [comment]
It has been fixed.
