### ISSUE TITLE
Why height and width are shortened?

### ISSUE THREAD

**Issue by rfoel** [gregberge/xstyled#390]
I usually do not use shortened props in order to improve readability, and upon looking [here](https://github.com/gregberge/xstyled/blob/main/packages/system/src/styles/sizing.ts#L34) and [here](https://github.com/gregberge/xstyled/blob/main/packages/system/src/styles/sizing.ts#L25) I wonder why height and width only exists in shortened version.

**Comment by gregberge** [comment]
Because on image they are real attributes. I wanted to avoid collision.

**Comment by rfoel** [comment]
I thought so. Is there a way to extend the API myself and include those?

Also, `marginX`, `marginY`, `paddingX`, and `paddingY` are not included, is there a reason for that?
