### ISSUE TITLE
TS error when trying to export xstyled with added utilities

### ISSUE THREAD

**Issue by yahor-ramanenka-op** [gregberge/xstyled#391]
## 🐛 Bug Report

TS error `Exported variable 'styled' has or is using name 'XStyled' from external module "file:///node_modules/@xstyled/styled-components/dist/index" but cannot be named.` when trying to export return value from `createCss`

## To Reproduce

1. Follow the guide on adding utilities https://xstyled.dev/docs/adding-new-utilities/
2. Try to `export {styled};`
3. Get an error.

## Expected behavior

No typescript error

## Link to repl or repo (highly encouraged)

[Typescript playground with issue](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgYwuCBnApgGhXSlwEMZcBhbbQ1bAT2wpEIF84AzKTOAIgACAD2YMANrgAmAelETJAWgxYAdrhUxsfANxIkGFc0Toa+OHKlmhZtCXK4A4mIgAjUmIDKMcbjgcAvMRkFNTYABRE0tJoAK7MvBZwAObquFDk0NhwABZpuETKkHhhjMy4IACUSBW6SLhCkLDGaKbm3vJWNnYUTq7uXj5+ukA)

## Run `npx envinfo --system --binaries --npmPackages @xstyled/system,@xstyled/styled-components,styled-components --markdown --clipboard`

```bash
## System:
 - OS: macOS 13.0.1
 - CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
 - Memory: 1.68 GB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - Yarn: 1.22.19 - ~/.yarn/bin/yarn
 - npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
## npmPackages:
 - @xstyled/styled-components: ^3.7.0 => 3.7.0 
 - styled-components: ^5.3.5 => 5.3.5 
```

**Comment by AhmedAymanOptio** [comment]
@gregberge are there any plans to release this fix? :)
