### ISSUE TITLE
Generated class names aren't legible

### ISSUE THREAD

**Issue by mintyfloss** [gregberge/xstyled#94]
## 🐛 Bug Report

Component class names are not using display names. They look like this:

```
<div class="sc-bdVaJa cyWyZX">
  Something
</div>
```
## To Reproduce

Here are my dependencies:

- @xstyled/styled-components 1.16.0
- @xstyled/system 1.16.0
- styled-components 4.4.1
- babel-plugin-styled-components 1.10.7

## Expected behavior

Previously without xstyled, I would get this class name in my styled components:

```
<div class="ComponentDisplayName_Text-sc-bdVaJa cyWyZX">
  Something
</div>
```

**Comment by hookydev** [comment]
Yeah, from version 1.10.3 babel-plugin-styled-components began to check if you use native instance of styled-components, so xstyled doesn't match. Try version 1.10.2, should work

**Comment by mintyfloss** [comment]
@hookydev Cool, pinning to 1.10.2 seems to work. Will I always have to pin to that version until `babel-plugin-styled-components` makes a change where they don't check for native instances? Or is there something that we can do in xstyled?

**Comment by hookydev** [comment]
I don't think babel-styled-components developers will change that behavior, even if we ask, cause they only support their own library. 
@gregberge, can we somehow fix that?

**Comment by reedham1** [comment]
+1

**Comment by gregberge** [comment]
I think the best option is to submit a PR to `babel-plugin-styled-components` to tell them to make the name of the package configurable. It is the safest way to do it.

**Comment by gregberge** [comment]
@mintyfloss @hookydev do you want to take the subject?

**Comment by bartels** [comment]
I see there is an old pull request which I think was looking to address this: https://github.com/styled-components/babel-plugin-styled-components/pull/122) 

It looks like the reason for making the change might not have been sufficiently explained.

**Comment by hookydev** [comment]
If someone still have interest to make **xstyled** working with latest version of **babel-plugin-styled-components**,  I've [forked](https://github.com/hookydev/babel-plugin-styled-components) the latest version and reverted some changes.

**Comment by pstoica** [comment]
Just chiming in to say this was fixed by https://github.com/styled-components/babel-plugin-styled-components/pull/288:

```
    ["styled-components", {
      "ssr": true,
      "topLevelImportPaths": [
        "@xstyled/styled-components",
        "@xstyled/styled-components/no-tags",
        "@xstyled/styled-components/native",
        "@xstyled/styled-components/primitives"
      ]
    }]
```

Worth adding to the docs!

**Comment by gregberge** [comment]
Fixed in v2.
